from dataclasses import dataclass
from typing import Dict, Any, Optional
from .base_agent import BaseAgent, AgentOutput
from .debate_room import DebateOutcome
from ..data.indicators import IndicatorSnapshot


@dataclass
class TradeProposal:
    """Actionable trade proposal generated by the Master Strategist."""
    symbol: str
    action: str  # "BUY", "SELL", "HOLD"
    target_entry_price: float
    stop_loss_price: float
    take_profit_price: float
    risk_reward_ratio: float
    confidence_score: float
    reasoning: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "symbol": self.symbol,
            "action": self.action,
            "target_entry_price": round(self.target_entry_price, 4),
            "stop_loss_price": round(self.stop_loss_price, 4),
            "take_profit_price": round(self.take_profit_price, 4),
            "risk_reward_ratio": round(self.risk_reward_ratio, 2),
            "confidence_score": round(self.confidence_score, 2),
            "reasoning": self.reasoning,
        }


class MasterStrategistAgent(BaseAgent):
    """Chief Investment Officer Agent that synthesizes all analyst inputs and debate results into actionable trade proposals."""

    SYSTEM_PROMPT = """You are the Chief Investment Officer (CIO) & Master Portfolio Strategist of an elite quantitative fund.
Your job is to review all analyst reports and the Bull vs. Bear debate, then issue a strictly formatted trade decision.

Output strictly valid JSON with this format:
{
    "symbol": "BTC/USDT",
    "action": "BUY",                    // "BUY", "SELL", or "HOLD"
    "target_entry_price": 65000.0,
    "stop_loss_price": 64200.0,
    "take_profit_price": 66600.0,
    "confidence_score": 0.85,           // Float between 0.0 and 1.0
    "reasoning": "Clear explanation of confluence across catalysts, flow, and technicals"
}"""

    def __init__(self, provider: str = "gemini", model_name: str = "gemini-2.5-flash"):
        super().__init__(
            name="MasterStrategistAgent",
            system_prompt=self.SYSTEM_PROMPT,
            provider=provider,
            model_name=model_name
        )

    def formulate_trade_proposal(
        self,
        symbol: str,
        current_price: float,
        indicators: IndicatorSnapshot,
        news_out: AgentOutput,
        flow_out: AgentOutput,
        tech_out: AgentOutput,
        macro_out: AgentOutput,
        debate: DebateOutcome
    ) -> TradeProposal:
        """Synthesizes all inputs and outputs a concrete TradeProposal."""
        atr = indicators.atr_14
        
        prompt = f"""Asset: {symbol}
Current Price: {current_price}
ATR (14): {atr}
Support Level: {indicators.support_level}
Resistance Level: {indicators.resistance_level}

Analyst Reports:
1. Macro Regime: {macro_out.summary} (Regime: {macro_out.details.get('macro_regime')})
2. News & Sentiment: {news_out.summary} (Score: {news_out.details.get('sentiment_score')})
3. Order Flow: {flow_out.summary} (Bias: {flow_out.details.get('flow_bias')})
4. Technical Setup: {tech_out.summary} (Bias: {tech_out.details.get('technical_bias')})

Debate Outcome:
Winner: {debate.winning_side} (Conviction: {debate.conviction_delta})
Bull Argument: {debate.bull_case}
Bear Argument: {debate.bear_case}

Formulate the final trade decision (BUY, SELL, or HOLD) with precise entry, stop loss, and take profit levels based on volatility (ATR). Output the required JSON."""

        raw_resp = self.call_llm(prompt)
        parsed = self.extract_json(raw_resp)

        action = parsed.get("action", "HOLD").upper()
        if action not in ["BUY", "SELL", "HOLD"]:
            action = "HOLD"

        # Fallback dynamic price levels based on ATR if unparsed or invalid
        if action == "BUY":
            stop_loss = float(parsed.get("stop_loss_price", current_price - (1.5 * atr)))
            take_profit = float(parsed.get("take_profit_price", current_price + (2.5 * atr)))
            entry = float(parsed.get("target_entry_price", current_price))
        elif action == "SELL":
            stop_loss = float(parsed.get("stop_loss_price", current_price + (1.5 * atr)))
            take_profit = float(parsed.get("take_profit_price", current_price - (2.5 * atr)))
            entry = float(parsed.get("target_entry_price", current_price))
        else:
            entry = current_price
            stop_loss = current_price * 0.98
            take_profit = current_price * 1.04

        risk_dist = abs(entry - stop_loss)
        reward_dist = abs(take_profit - entry)
        rr_ratio = (reward_dist / (risk_dist + 1e-10)) if risk_dist > 0 else 1.5

        confidence = float(parsed.get("confidence_score", 0.70))
        reasoning = parsed.get("reasoning", f"Trade proposal generated based on confluence of {debate.winning_side} momentum and technical setup.")

        return TradeProposal(
            symbol=symbol,
            action=action,
            target_entry_price=entry,
            stop_loss_price=stop_loss,
            take_profit_price=take_profit,
            risk_reward_ratio=rr_ratio,
            confidence_score=confidence,
            reasoning=reasoning
        )

    def _heuristic_fallback(self, prompt: str) -> str:
        import json
        import re

        # Extract current price and ATR from prompt dynamically if available
        price_match = re.search(r"Current Price:\s*([\d\.]+)", prompt)
        atr_match = re.search(r"ATR \(14\):\s*([\d\.]+)", prompt)

        current_price = float(price_match.group(1)) if price_match else 65000.0
        atr = float(atr_match.group(1)) if atr_match else (current_price * 0.015)

        entry = current_price
        stop_loss = current_price - (1.5 * atr)
        take_profit = current_price + (2.5 * atr)

        return json.dumps({
            "action": "BUY",
            "target_entry_price": round(entry, 4),
            "stop_loss_price": round(stop_loss, 4),
            "take_profit_price": round(take_profit, 4),
            "confidence_score": 0.82,
            "reasoning": "Strong multi-factor confluence between order book accumulation, positive sentiment, and technical breakout."
        })
